### ISSUE TITLE
Template Error in Commerce Email?

### ISSUE THREAD

**Issue by jacobgraf** [jonathanmelville/s3securedownloads#5]
I am using your plugin to generate a download link in a Commerce email. Everything works fine when I test the email template in the browser, but when Craft tries to generate and send the Commerce email, I get the following error. Any ideas?

`2020-02-20 06:04:21 [-][1][-][error][craft\commerce\services\Emails::sendEmail] Email template parse error for email “Event - Registration”. Order: “da45cef”. Template error: “Unknown "getSignedUrl" function.” /home/forge/getconnected.works/templates/_emails/events/registrationBsp1.twig:19`

**Craft:** Pro 3.4.6.1
**Commerce:** Pro 3.0.9
**S3 Secure Downloads:** 2.2.1

**Comment by jonathanmelville** [comment]
@jacobgraf Im curious you are are even using this plugin in Craft 3 as it was written for Craft 2 😎. 

I have considered releasing a new version for Craft 3 but have not done so as of right now and I'm not actively supporting this plugin. Feel free to hit me up on the Craft Discord and I might be able to help you work out a solution though.
